name: xafit
description: "XaFit - App de entrenamiento personal offline-first desarrollada en Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  fl_chart: ^1.1.1
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  flutter_timezone: ^5.0.1
  drift: ^2.32.0
  drift_flutter: ^0.3.0
  path_provider: ^2.1.5
  file_picker: ^8.1.2
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/icon.png
     
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/icon.png"
  remove_alpha_ios: true

  adaptive_icon_background: "#0F1115"
  adaptive_icon_foreground: "lib/assets/icon/icon_foreground.png"
  adaptive_icon_foreground_inset: 8